/*
  View switching, tab-sync, and hash-based deep-linking (QR targets).
  Unchanged in behavior from the original mockup — extracted verbatim so a
  new stop only ever needs an entry in data/stops.js, never an edit here.
*/
function show(id) {
  function swap() {
    if (!document.getElementById(id)) id = 'welcome'; // unknown target -> home
    // stop any narration when leaving a view (produced audio or the TTS fallback)
    if (typeof window.stopNarration === 'function') { window.stopNarration(); }
    if ('speechSynthesis' in window) { window.speechSynthesis.cancel(); }
    document.querySelectorAll('.audio-btn').forEach(function (b) { b.textContent = '▶ Listen'; });
    document.querySelectorAll('.view').forEach(function (v) { v.classList.remove('active'); });
    var el = document.getElementById(id);
    if (el) el.classList.add('active');
    // let js/beats.js know a stop view just became active, so it can reset
    // that stop's beat position to Arrive -- beat position is transient UI
    // state, not part of the URL hash, so it can't be restored from here.
    if (el && el.hasAttribute('data-stop-section')) {
      document.dispatchEvent(new CustomEvent('view:activated', { detail: { id: id } }));
    }
    // sync bottom tabs (any stop view maps to the Stops tab)
    var tabFor = (id.indexOf('stop') === 0) ? 'map' : id;
    document.querySelectorAll('.tabbar button').forEach(function (b) { b.classList.remove('active'); });
    var tab = document.getElementById('tab-' + tabFor);
    if (tab) tab.classList.add('active');
    // keep the URL hash in sync so the page is deep-linkable (QR targets).
    // replaceState does NOT fire hashchange, so this can't loop.
    if (('#' + id) !== location.hash) {
      try { history.replaceState(null, '', location.pathname + location.search + '#' + id); }
      catch (e) { /* file:// in some browsers blocks replaceState — safe to ignore */ }
    }
  }
  // Scroll to top immediately before transition starts
  window.scrollTo({ top: 0, behavior: 'instant' in window ? 'instant' : 'auto' });
  // Progressive enhancement: morphs a tapped .stopcard thumbnail into the
  // stop's hero photo (matching view-transition-name, set in render.js).
  // Unsupported browsers (partial Safari support) just run swap() directly.
  if (typeof document.startViewTransition === 'function') {
    document.startViewTransition(swap);
  } else {
    swap();
  }
}

// Deep-linking: a QR code encodes e.g. tour-app-mockup.html#stop2 and the
// camera opens straight to that stop. Handles first load and hash changes.
function routeFromHash() {
  var id = (location.hash || '').replace(/^#/, '');
  if (id) show(id);
}
window.addEventListener('hashchange', routeFromHash);

// Stop sections are generated by render.js at DOMContentLoaded; route only
// after they exist so a deep link into a dynamically-built stop works.
window.afterRender = routeFromHash;

/*
  Theme toggle — switches between light and dark mode. Preference is saved
  to localStorage and restored on page load.
*/
function toggleTheme() {
  var html = document.documentElement;
  var btn = document.getElementById('theme-toggle');
  var currentTheme = html.getAttribute('data-theme');
  var newTheme = currentTheme === 'dark' ? 'light' : 'dark';

  html.setAttribute('data-theme', newTheme);
  btn.textContent = newTheme === 'dark' ? '🚀' : '🌙';
  btn.setAttribute('aria-label', newTheme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode');

  // Save preference
  try {
    localStorage.setItem('theme', newTheme);
  } catch (e) { /* localStorage unavailable in some contexts */ }
}

// Restore theme preference on page load
(function() {
  try {
    var savedTheme = localStorage.getItem('theme');
    var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
    var theme = savedTheme || (prefersDark ? 'dark' : 'light');

    if (theme === 'dark') {
      document.documentElement.setAttribute('data-theme', 'dark');
      var btn = document.getElementById('theme-toggle');
      if (btn) {
        btn.textContent = '☀️';
        btn.setAttribute('aria-label', 'Switch to light mode');
      }
    }
  } catch (e) { /* safe to ignore */ }
})();
