/*
  Narration playback for each stop.

  Primary path: play the produced audio file pre-generated by
  gen_narration.py (data/stops.js -> narration.audio), rendered into the
  page by render.js as data-audio-src on the .audio-btn. This is real
  produced speech, not a device voice, and it's a normal <audio> element
  under the hood -- cacheable, works offline once loaded, no per-play cost.

  Fallback: if a stop has no produced audio yet (data-audio-src missing) or
  the file fails to load, fall back to the browser's built-in
  speechSynthesis so the button never just does nothing. That fallback is
  intentionally the *lower* bar -- it should only ever be visible while a
  stop's audio hasn't been generated yet.
*/
var _narrationAudio = null; // the single <audio> element currently in use, if any

function _resetNarrationBtn(btn) {
  btn.textContent = '\u25B6 Listen';
}

function toggleTranscript(btn) {
  var audioPlayer = btn.closest('.audio-player');
  if (!audioPlayer) return;

  var transcript = audioPlayer.querySelector('.transcript');
  if (!transcript) return;

  var isHidden = transcript.hidden;
  transcript.hidden = !isHidden;
  btn.textContent = isHidden ? 'Hide transcript' : 'Show transcript';
}

function _stopAudioPlayback(btn) {
  if (_narrationAudio) {
    _narrationAudio.pause();
    _narrationAudio.currentTime = 0;
    _narrationAudio = null;
  }
  if (btn) _resetNarrationBtn(btn);
}

function _playProducedAudio(btn, src) {
  var audio = new Audio(src);
  _narrationAudio = audio;
  var stopId = btn.getAttribute('data-stop-id');
  // Beat sequence (js/beats.js) drives cue-point reveals and the scrub bar
  // off these events rather than polling _narrationAudio directly -- kept
  // event-based so this module's playback state stays private.
  audio.addEventListener('play', function () {
    document.dispatchEvent(new CustomEvent('narration:play', { detail: { stopId: stopId } }));
  });
  audio.addEventListener('timeupdate', function () {
    document.dispatchEvent(new CustomEvent('narration:timeupdate', {
      detail: { stopId: stopId, currentTime: audio.currentTime, duration: audio.duration }
    }));
  });
  audio.addEventListener('ended', function () {
    if (_narrationAudio === audio) _narrationAudio = null;
    _resetNarrationBtn(btn);
    document.dispatchEvent(new CustomEvent('narration:ended', { detail: { stopId: stopId } }));
  });
  audio.addEventListener('error', function () {
    if (_narrationAudio === audio) _narrationAudio = null;
    // Produced file missing/broken -- fall back to device speech rather
    // than leaving the button stuck on "Stop" with nothing playing.
    _speakWithBrowserTts(btn);
  });
  audio.play().catch(function () {
    _speakWithBrowserTts(btn);
  });
  btn.textContent = '\u23F8 Stop';
}

function _speakWithBrowserTts(btn) {
  if (!('speechSynthesis' in window)) {
    alert('Mockup: a produced, cleared audio track would play here.');
    _resetNarrationBtn(btn);
    return;
  }
  var text = btn.getAttribute('data-narration') || '';
  var u = new SpeechSynthesisUtterance(text);
  u.rate = 0.96;
  u.onend = function () { _resetNarrationBtn(btn); };
  window.speechSynthesis.speak(u);
  btn.textContent = '\u23F8 Stop';
}

function toggleNarration(btn) {
  var isPlaying = (_narrationAudio && !_narrationAudio.paused) ||
    ('speechSynthesis' in window && window.speechSynthesis.speaking);
  if (isPlaying) {
    _stopAudioPlayback(btn);
    if (window.speechSynthesis) window.speechSynthesis.cancel();
    return;
  }
  var src = btn.getAttribute('data-audio-src');
  if (src) {
    _playProducedAudio(btn, src);
  } else {
    _speakWithBrowserTts(btn);
  }
}

// Called by app.js's show() when navigating away from a view, so audio
// never keeps playing under a different stop.
function stopNarration() {
  _stopAudioPlayback(null);
}
window.stopNarration = stopNarration;

// Called by js/beats.js when the user drags the Narrate beat's scrub bar.
// Only meaningful while produced audio is playing -- the TTS fallback has
// no seekable timeline.
function seekNarration(time) {
  if (_narrationAudio) { _narrationAudio.currentTime = time; }
}
window.seekNarration = seekNarration;
